Mobile Menu
fitz95/Portfolio-Microverse- pull request #11
Opened 2022-12-20 13:58 UTC by fitz95

- change mobile menu so user clicks (or taps) the hamburger button, the mobile menu appears.
  - change mobile menu so user clicks (or taps) the close (X) button, the mobile menu disappears.
  - change mobile menu so the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
  - change mobile menu so the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed

2022-12-20 14:05 UTC, Munsa1 requested changes
Hi @fitz95, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a failing linter test for javascript

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-20 17:15 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi Team! @fitz95 @PrinceBadru @Sammy3000, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-20 17:15 UTC, anagudelogu commented on index.html
> +      </div>
You did a great job working on your mobile menu! 🚀 In fact, all the functionality is working as expected, but according to the requirements, you should stick as much as possible to the Figma design 🎨.

- [ ] Please consider using the correct background image for the menu. 🚧 
- [ ] Please consider using the font provided by the template as well as the correct color. 🚧 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/208725184-b0a96b10-1ca4-42d6-b9ac-c33215656019.png) | ![image](https://user-images.githubusercontent.com/77069011/208725045-acb7ae2e-fec4-454d-98b9-5cf198c7bf97.png) |

Having a good-looking and consistent design will show future recruiters what you're capable of and also catch their attention! So please consider investing some time in applying these changes. 🤓 🛠️

2022-12-20 17:15 UTC, anagudelogu commented on myScript.js
> +  // li[len].classList.add('active');
- [ ] Please consider removing all pieces of commented code from your codebase as this will keep it cleaner and improve its readability! 🤓 🛠️

2022-12-21 08:39 UTC, FrederickMih approved these changes
## Hi :raising_hand:  @fitz95  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights :green_circle: 

- All Linter checks passed :heavy_check_mark: 
- Mobile menu design matches that of Figma :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-21 08:39 UTC, FrederickMih commented on index.html
> +          <a href="#form" onclick="closeNav()">Contact</a>
- [Optional] The correct page was not displayed after clicking on this link. Please let's consider fixing it.

2022-12-21 08:43 UTC, merged